#ifndef APPLICATIONCONFIG_H
#define APPLICATIONCONFIG_H

#include <QString>

namespace Enginio {

const QByteArray BACKEND_ID("REPLACE_WITH_YOUR_BACKEND_ID");
const QByteArray BACKEND_SECRET("REPLACE_WITH_YOUR_BACKEND_SECRET");

}

#endif // APPLICATIONCONFIG_H
